id = "haxe-support"
name = "Haxe Support"
version = "0.0.1"
schema_version = 1
authors = ["Thomas J. Webb <thomas@osakared.com>"]
description = "Support for the Haxe programming language"
repository = "https://github.com/your-name/my-zed-extension"

[grammars.haxe]
repository = "https://github.com/vantreeseba/tree-sitter-haxe"
commit = "5f7a2e09b5885d2aa6d60d2d6e5a9de3823e813c"